### ISSUE TITLE
Skip the limit

### ISSUE THREAD

**Issue by Iastre** [cps209teamalpha/space-alien#49]
I'm seeing some frightening 'if' statements in the code. Here's a generic example:

Say var is a variable that gets decremented (var--;) by certain events:

if (var == 0)
{
...
}

This code looks alright, but it's not. If var happens to be 1, what will happen if it gets decremented (var--;) twice before the if statement can be called? This is a bug that my roommate had in his C++ team project, and it's easily fixed:

if (var <= 0)
{
...
}

The same is true for upper limits as well (things such as bounds checking, etc.). It might be good to just look through the code and change any place where (var == number) is used to either (var <= number) or (var >= number). Unless, of course, the test is supposed to do a precise equals comparison.

**Comment by imora128** [comment]
I'll take a look at this after classes.

**Comment by imora128** [comment]
I looked through anything involving a == comparison and only found 2 situations which fit what you described. We really don't do too much comparison outside of the network code.

**Comment by imora128** [comment]
I went through the code and only found 2 instances of what could possibly be issues regarding what you're talking about. We really don't do much comparison outside of the network portion of the code.

**Comment by Iastre** [comment]
Okay, that's good. I was initially worried about the level checking to see how many enemies were left - if that got decremented twice at once, the level advance would break. But I rewrote that particular variable to look at the size of the enemies vector anyway, which can't ever be less than 0.

I just know this is something that bit my roommate's team for their C++ game, so I want to be sure we don't encounter any problems related to that.
